pharmclient-main/pharmclient-main/Controllers/ProdController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PharmClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace PharmClient.Controllers
{
    public class ProdController : Controller
    {
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(ProdController));
        public async Task<ActionResult> Productdetails()
        {
            _log4net.Info("The Product list is displayed");
            List<Product> ProductInfo = new List<Product>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                //client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("https://localhost:44329/api/Product");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    ProductInfo = JsonConvert.DeserializeObject<List<Product>>(EmpResponse);

                }
                //returning the employee list to view  
                return View(ProductInfo);
            }
        }


        public async Task<ActionResult> AddtoCart(Product pro)
        {
            _log4net.Info("The product " + pro.Productname + " has been added to the cart");
            int uid = (int)HttpContext.Session.GetInt32("userid");
            AddtoCart cartobj = new AddtoCart();
            cartobj.Userid = uid;
            cartobj.Productid = pro.Productid;
            cartobj.ProductImage = pro.ProductImage;
            cartobj.Productname = pro.Productname;
            cartobj.ProductDesc = pro.ProductDesc;
            cartobj.Price = pro.Price;
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(cartobj), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44329/api/Product", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //cartobj = JsonConvert.DeserializeObject<AddtoCart>(apiResponse);
                }
            }
            return RedirectToAction("Productdetails");
        }

        public async Task<ActionResult> Cartdetails(AddtoCart atc)
        {
            _log4net.Info("The cart products are displayed");
            int uid = (int)HttpContext.Session.GetInt32("userid");
            List<AddtoCart> CartInfo = new List<AddtoCart>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                //client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("https://localhost:44329/api/Product/GetCartByUserId?Userid=" + uid);

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var CartResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    CartInfo = JsonConvert.DeserializeObject<List<AddtoCart>>(CartResponse);

                }
                //returning the employee list to view  
                return View(CartInfo);

            }
        }
        
        public async Task<ActionResult> Delete(int id)
        {

            _log4net.Info("The product with id " + id + " is deleted");
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:44329/api/Product?id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            _log4net.Info("Product deleted redirected to Cart");
            ViewBag.Username = HttpContext.Session.GetString("username");return RedirectToAction("Cartdetails");
        }
        public async Task<ActionResult> Orderdetails()
        {
            _log4net.Info("The order details are diplayed");
            ViewBag.Username = HttpContext.Session.GetString("username");
            int uid = (int)HttpContext.Session.GetInt32("userid");
            List<AddtoCart> OrderInfo = new List<AddtoCart>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                //client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("https://localhost:44329/api/Product/GetCartByUserId?Userid=" + uid);

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var OrderResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    OrderInfo = JsonConvert.DeserializeObject<List<AddtoCart>>(OrderResponse);

                }
                //returning the employee list to view  
                return View(OrderInfo);

            }
        }
    }
}

pharmclient-main/pharmclient-main/Controllers/ProfController.cs
using JWT;
using JWT.Algorithms;
using JWT.Serializers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using PharmClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace PharmClient.Controllers
{
    public class ProfController : Controller
    {
        string Token = "";

        IConfiguration _config;

        private IJsonSerializer _serializer = new JsonNetSerializer();
        private IDateTimeProvider _provider = new UtcDateTimeProvider();
        private IBase64UrlEncoder _urlEncoder = new JwtBase64UrlEncoder();
        private IJwtAlgorithm _algorithm = new HMACSHA256Algorithm();
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(ProfController));

        public ProfController(IConfiguration config)
        {
            _config = config;
        }

        [HttpGet]
        public async Task<ActionResult> ViewProfile()
        {

            int uid = (int)HttpContext.Session.GetInt32("userid");
            _log4net.Info("Inside Profile View of User "+uid);
            CustomerDetail c = new CustomerDetail();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44393/api/Profile/" + uid))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    c = JsonConvert.DeserializeObject<CustomerDetail>(apiResponse);
                }
            }
            return View(c);
        }
        [HttpGet]
        public async Task<ActionResult> EditProfile()
        {
            CustomerDetail c = new CustomerDetail();
            int id =(int) HttpContext.Session.GetInt32("userid");
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Token);
                var res = await client.GetAsync("https://localhost:44393/api/Profile/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    c = JsonConvert.DeserializeObject<CustomerDetail>(result);
                }
            }
            return View(c);
        }
        [HttpGet]
        public IActionResult EditLogin()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> EditLogin(CustomerDetail e)
        {
            //int id = (int)HttpContext.Session.GetInt32("UserId");
            //string Token = HttpContext.Request.Cookies["Token"];
            CustomerDetail receivedemp = new CustomerDetail();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Token);
                StringContent editcon = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");
                var res = await client.PostAsync("https://localhost:44383/api/CustomerDetail/CustomerLogin", editcon);
                if (res.IsSuccessStatusCode)
                {

                    return RedirectToAction("EditProfile");
                        
                }
            }
            return RedirectToAction("ViewProfile");
        }
        [HttpPost]
        public async Task<ActionResult> EditProfile(CustomerDetail e)
        {
            _log4net.Info(" Profile is edited");
            CustomerDetail receivedemp = new CustomerDetail();
            using (var httpClient = new HttpClient())
            {
                int id = e.Userid;
                StringContent content1 = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("https://localhost:44393/api/Profile?id=" + id, content1))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Result = "Success";
                    receivedemp = JsonConvert.DeserializeObject<CustomerDetail>(apiResponse);
                }
            }
            return RedirectToAction("ViewProfile");
        }
    }
}

pharmclient-main/pharmclient-main/Views/Prod/Cartdetails.cshtml
@model IEnumerable<PharmClient.Models.AddtoCart>

@{
    ViewData["Title"] = "Cartdetails";
    decimal total = 0;
}

<style>
    th {
        color: white;
    }
    input:hover[type="submit"] {
        border-radius: 20%;
        border: none;
        border-color: bisque;
        background-color: antiquewhite;
    }

    input.slide-hover-left-1 {
        background-image: linear-gradient(0, #156760, #156760);
        background-size: 0;
        transition: .8s;
        background-repeat: no-repeat;
    }

        input.slide-hover-left-1:hover {
            background-size: 100%;
            color: #fff;
        }

    button:hover[type="submit"] {
        border-radius: 20%;
        border: none;
        border-color: bisque;
        background-color: antiquewhite;
    }

    button.slide-hover-left-1 {
        background-image: linear-gradient(0, #156760, #156760);
        background-size: 0;
        transition: .8s;
        background-repeat: no-repeat;
    }

        button.slide-hover-left-1:hover {
            background-size: 100%;
            color: #fff;
        }
    td {
        color: #156760;
    }
</style>
<div style="width =100%; background-color: #A2ECE6;border:none;">
    <h1 style="color: #156760;text-align:center">Orderdetails</h1>
    <br />
    <h4 style="color: #156760;text-align:center">Hello @ViewBag.Username!! Here are your Orders</h4>
</div>


<table class="table">
    <thead>
        <tr style="background-color: #156760">
            @*<th>
                Cart Id
            </th>
            <th>
                User ID
            </th>
            <th>
                Product ID
            </th>*@
            <th>
                Product
            </th>
            <th>
                Product Name
            </th>
            <th>
                Description
            </th>
            <th>
                Price
            </th>
            <th>

            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr style="background-image: linear-gradient(to right,white,white,#A2ECE6);width:100%">
            @*<td style="color: #156760">
                @Html.DisplayFor(modelItem => item.Cartid)
            </td>
            <td style="color: #156760">
                @Html.DisplayFor(modelItem => item.Userid)
            </td>
            <td style="color: #156760">
                @Html.DisplayFor(modelItem => item.Productid)
            </td>*@
            <td style="color: #156760">
                <img src="@Url.Content(item.ProductImage)" alt="no data" height="100" width="100" />
            <td style="color: #156760">
                @Html.DisplayFor(modelItem => item.Productname)
            </td>
            <td style="color: #156760">
                @Html.DisplayFor(modelItem => item.ProductDesc)
            </td>
            <td style="color: #156760">
                Rs.@Html.DisplayFor(modelItem => item.Price)
            </td>

            
            <td> <a asp-action="Delete" asp-route-id="@item.Cartid" onclick="return confirm('Are you sure you want to delete this product?')"><img src="~/Images/delete.png" width="35" height="35" /></a> </td>
        </tr>
            total = total + Convert.ToDecimal(item.Price);
        }
    </tbody>
</table>

<div style="width =100%; background-color: #A2ECE6;border:none;">
    <h5 style="color: #156760;text-align:right;">Your total price is Rs.@total</h5>
    <br />
    <a onclick="location.href='@Url.Action("Payment", "Payment")'"><button class="btn btn-primary slide-hover-left-1" style="background-color: #1D8D84; border: none; padding: 7px 30px; color: white">Buy now</button></a>
    <a onclick="location.href='@Url.Action("Productdetails", "Prod")'"><button class="btn btn-primary slide-hover-left-1" style="background-color: #1D8D84; border: none; padding: 7px 30px; color: white">Back to products</button></a>
</div>

pharmclient-main/pharmclient-main/Views/Prod/Orderdetails.cshtml
@model IEnumerable<PharmClient.Models.AddtoCart>

@{
    ViewData["Title"] = "Orderdetails";
}

<style>
    th {
        color: white;
    }
    input:hover[type="submit"] {
        border-radius: 20%;
        border: none;
        border-color: bisque;
        background-color: antiquewhite;
    }

    input.slide-hover-left-1 {
        background-image: linear-gradient(0, #156760, #156760);
        background-size: 0;
        transition: .8s;
        background-repeat: no-repeat;
    }

        input.slide-hover-left-1:hover {
            background-size: 100%;
            color: #fff;
        }

    button:hover[type="submit"] {
        border-radius: 20%;
        border: none;
        border-color: bisque;
        background-color: antiquewhite;
    }

    button.slide-hover-left-1 {
        background-image: linear-gradient(0, #156760, #156760);
        background-size: 0;
        transition: .8s;
        background-repeat: no-repeat;
    }

        button.slide-hover-left-1:hover {
            background-size: 100%;
            color: #fff;
        }
    td {
        color: #156760;
    }
</style>
<div style="width =100%; background-color: #A2ECE6;border:none;">
    <h1 style="color: #156760;text-align:center">Orderdetails</h1>
    <br />
    <h4 style="color: #156760;text-align:center">Hello @ViewBag.Username!! Here are your Orders</h4>
</div>


<table class="table">
    <thead>
        <tr style="background-color: #156760">
            <th>
                Cart Id
            </th>
            <th>
                User ID
            </th>
            <th>
                Product ID
            </th>
            <th>
                Product
            </th>
            <th>
                Product Name
            </th>
            <th>
                Description
            </th>
            <th>
                Price
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr style="background-image: linear-gradient(to right,white,white,#A2ECE6);width:100%">
                <td style="color: #156760">
                    @Html.DisplayFor(modelItem => item.Cartid)
                </td>
                <td style="color: #156760">
                    @Html.DisplayFor(modelItem => item.Userid)
                </td>
                <td style="color: #156760">
                    @Html.DisplayFor(modelItem => item.Productid)
                </td>
                <td style="color: #156760">
                    <img src="@Url.Content(item.ProductImage)" alt="no data" height="100" width="100" />
                <td style="color: #156760">
                    @Html.DisplayFor(modelItem => item.Productname)
                </td>
                <td style="color: #156760">
                    @Html.DisplayFor(modelItem => item.ProductDesc)
                </td>
                <td style="color: #156760">
                    Rs.@Html.DisplayFor(modelItem => item.Price)
                </td>

            </tr>
        }
    </tbody>
</table>
<div style="width =100%; background-color: #A2ECE6;border:none;">
    <h5 style="color: #156760;">Thank you for ordering!!!</h5>
    <br />
    <a onclick="location.href='@Url.Action("Productdetails", "Prod")'"><button class="btn btn-primary slide-hover-left-1" style="background-color: #1D8D84; border: none; padding: 7px 30px; color: white">Back to products</button></a>
</div>

pharmclient-main/pharmclient-main/Views/Prod/Productdetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<PharmClient.Models.Product>
<style>
    #divprofile {
        border: solid;
    }
    input:hover[type="submit"] {
        border-radius: 20%;
        border: none;
        border-color: bisque;
        background-color: antiquewhite;
    }

    input.slide-hover-left-1 {
        background-image: linear-gradient(0, #156760, #156760);
        background-size: 0;
        transition: .8s;
        background-repeat: no-repeat;
    }

        input.slide-hover-left-1:hover {
            background-size: 100%;
            color: #fff;
        }

    button:hover[type="submit"] {
        border-radius: 20%;
        border: none;
        border-color: bisque;
        background-color: antiquewhite;
    }

    button.slide-hover-left-1 {
        background-image: linear-gradient(0, #156760, #156760);
        background-size: 0;
        transition: .8s;
        background-repeat: no-repeat;
    }

        button.slide-hover-left-1:hover {
            background-size: 100%;
            color: #fff;
        }
    #itemdiv {
        position: relative;
        margin-bottom: 25px;
    }

    #div1 {
        text-align: center;
    }

    h6 {
        color: #156760;
    }
</style>
<body>

    <div class="container">
        <div class="row">
            <div class="col">
                <div class="row">
                    @foreach (var pro in Model)
                    {
                        <div class="col-lg-4">
                            <div class="card" id="itemdiv" style=" background-image: linear-gradient(to bottom,white,white,#A2ECE6);">
                                <div class="card-body" id="div1">
                                    @*<h6>@pro.Productid</h6>*@
                                    <img src="@Url.Content(pro.ProductImage)" alt="no data" height="100" width="100" />
                                    <h4 style="color: #156760">@pro.Productname</h4>
                                    <h6>@pro.ProductDesc</h6>
                                    <h4 style="color: #2F4F4F">Rs.@pro.Price</h4>

                                </div>
                                <input type="button" value="Addtocart" class="btn btn-primary slide-hover-left-1" onclick="location.href = '@Url.Action("AddtoCart", "Prod",pro)';return confirm ('Product Added');" style="background-color: #1D8D84; border: none; " />
                            </div>
                        </div>
                    }
                </div>
            </div>
            @*<div class="col-3" id="divprofile"style=" background-image: linear-gradient(to bottom,white,white,#A2ECE6);">
                <center>
                    <img src="~/Images/Profile.png" alt="nodata" height="100" width="100" /><br />
                    <a asp-action="ViewProfile" asp-controller="Prof" class="btn btn-primary" style="background-color: #156760;border:none;  ">View Profile</a>
                    <hr />
                    <a asp-action="Cartdetails" asp-controller="Prod"class="btn btn-primary" style="background-color: #156760;border:none;  ">Cart Details</a>
                    <hr />
                    <a asp-action="CancelOrder" asp-controller="Order" onclick="return confirm ('Are you sure want to cancel ?')" class="btn btn-primary" style="background-color: #156760;border:none;  ">Cancel Order</a>
                    <hr />
                    <a asp-action="Myorders" asp-controller="Order" class="btn btn-primary" style="background-color: #156760;border:none;  " onclick="location.href='@Url.Action(" Myorders", "Order" )'">My Orders</a>
                </center>
            </div>*@
        </div>
    </div>
</body>
@*onclick="location.href='@Url.Action("Productdetails", "Prod")'*@